# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mayastorCP:
  registry:
  pullPolicy: Always
  logLevel: info

base:
  initContainers:
    enabled: true
    containers:
      - name: nats-probe
        image: busybox:latest
        command: [ 'sh', '-c', 'trap "exit 1" TERM; until nc -vz nats 4222; do echo "Waiting for nats..."; sleep 1; done;' ]
      - name: etcd-probe
        image: busybox:latest
        command: [ 'sh', '-c', 'trap "exit 1" TERM; until nc -vz mayastor-etcd 2379; do echo "Waiting for etcd..."; sleep 1; done;' ]

  imagePullSecrets:
    enabled: true
    secrets:
      - name: regcred

  jaeger:
    enabled: false
    initContainer: true
    agent:
      name: jaeger-agent
      port: 6831
      initContainer:
        - name: jaeger-probe
          image: busybox:latest
          command: [ 'sh', '-c', 'trap "exit 1" TERM; until nc -vz -u {{.Values.base.jaeger.agent.name}} {{.Values.base.jaeger.agent.port}}; do echo "Waiting for jaeger..."; sleep 1; done;' ]

operators:
  pool:
    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "250m"
        memory: "500Mi"

jaeger-operator:
  name: "mayastor"
  crd:
    install: false
  jaeger:
    create: false
  rbac:
    clusterRole: true
