[profile.dev]
panic = "abort"

[workspace]
members = [
    "common",
    "control-plane/agents",
    "control-plane/msp-operator",
    "control-plane/rest",
    "control-plane/csi/controller",
    "control-plane/csi/node-plugin",
    "control-plane/grpc",
    "deployer",
    "kubectl-plugin",
    "openapi",
    "rpc",
    "utils/utils-lib",
    "utils/pstor-usage",
    "utils/mayastor-dependencies/composer",
    "utils/mayastor-dependencies/devinfo",
    "utils/mayastor-dependencies/nvmeadm",
    "utils/mayastor-dependencies/sysfs",
    # Test mayastor through the rest api
    "tests/tests-mayastor",
]
