apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: core-agents
  namespace: mayastor
  labels:
    app: core-agents
spec:
  serviceName: core-agents
  replicas: 1
  selector:
    matchLabels:
      app: core-agents
  template:
    metadata:
      labels:
        app: core-agents
    spec:
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      initContainers:
        {{- include "base_init_containers" . }}
      containers:
        - name: core
          image: {{ .Values.mayastorCP.registry }}mayadata/mcp-core:{{ .Values.mayastorCP.tag }}
          imagePullPolicy: {{ .Values.mayastorCP.pullPolicy }}
          args:
            - "-smayastor-etcd"
            - "-nnats"
            - "--request-timeout={{ .Values.base.default_req_timeout }}"
            - "--cache-period={{ .Values.base.cache_poll_period }}"{{ if .Values.base.jaeger.enabled }}
            - "--jaeger={{ .Values.base.jaeger.agent.name }}:{{ .Values.base.jaeger.agent.port }}"{{ end }}