apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: mayastor
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      initContainers:
        {{- include "base_init_containers" . }}
      containers:
        - name: rest
          image: {{ .Values.mayastorCP.registry }}mayadata/mcp-rest:{{ .Values.mayastorCP.tag}}
          imagePullPolicy: {{ .Values.mayastorCP.pullPolicy }}
          args:
            - "--dummy-certificates"
            - "--no-auth"
            - "-nnats"
            - "--http=0.0.0.0:8081"
          ports:
          - containerPort: 8080
          - containerPort: 8081
