[package]
name = "rest"
version = "0.1.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rest"
path = "./service/src/main.rs"

[lib]
name = "rest_client"
path = "./src/lib.rs"

[dependencies]
# Actix Server, Client and telemetry
rustls = "0.19.1"
actix-web = { version = "4.0.0-beta.9", features = ["rustls"] }
actix-service = "2.0.0"
opentelemetry-jaeger = { version = "0.15.0", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = "0.15.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
actix-web-opentelemetry = "0.11.0-beta.5"
actix-http = "3.0.0-beta.10"
awc = "3.0.0-beta.8"

async-trait = "0.1.51"
serde_json = { version = "1.0.68", features = ["preserve_order"] }
serde_yaml = "0.8.21"
structopt = "0.3.23"
futures = "0.3.17"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
tracing-futures = "0.2.5"
strum = "0.21.0"
strum_macros = "0.21.1"
anyhow = "1.0.44"
snafu = "0.6.10"
url = "2.2.2"
http = "0.2.5"
tinytemplate = "1.2.1"
jsonwebtoken = "7.2.0"
common-lib = { path = "../../common" }
humantime = "2.1.0"

[dev-dependencies]
rpc = { path = "../../rpc"}
tokio = { version = "1.12.0", features = ["full"] }
actix-rt = "2.2.0"
composer = { path = "../../composer" }
ctrlp-tests = { path = "../../tests/tests-mayastor" }

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
