---
# Source: mayastor-control-plane/charts/jaeger-operator/templates/role-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mayastor-jaeger-operator
  namespace: mayastor
  labels:
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: mayastor
subjects:
- kind: ServiceAccount
  namespace: mayastor
  name: mayastor-jaeger-operator
roleRef:
  kind: ClusterRole
  name: mayastor-jaeger-operator
  apiGroup: rbac.authorization.k8s.io
