---
# Source: mayastor-control-plane/charts/jaeger-operator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mayastor-jaeger-operator
  namespace: mayastor
  labels:
    app.kubernetes.io/name: jaeger-operator
    app.kubernetes.io/instance: mayastor
